#!/usr/bin/env bash
set -euo pipefail

host_user="${1:-${SUDO_USER:-${USER:-}}}"

if [[ -z "${host_user}" ]]; then
  echo "usage: $0 [host-user]" >&2
  exit 2
fi

passwd_entry="$(getent passwd "${host_user}" || true)"
if [[ -z "${passwd_entry}" ]]; then
  echo "host user not found: ${host_user}" >&2
  exit 1
fi

host_uid="$(printf '%s\n' "${passwd_entry}" | awk -F: '{print $3}')"
host_gid="$(printf '%s\n' "${passwd_entry}" | awk -F: '{print $4}')"
host_home="$(printf '%s\n' "${passwd_entry}" | awk -F: '{print $6}')"
container_user="docker_${host_user}"

tz="Etc/UTC"
if command -v timedatectl >/dev/null 2>&1; then
  detected_tz="$(timedatectl show -p Timezone --value 2>/dev/null || true)"
  if [[ -n "${detected_tz}" ]]; then
    tz="${detected_tz}"
  fi
elif [[ -f /etc/timezone ]]; then
  detected_tz="$(sed -n '1p' /etc/timezone)"
  if [[ -n "${detected_tz}" ]]; then
    tz="${detected_tz}"
  fi
fi

locale_value=""
if command -v localectl >/dev/null 2>&1; then
  locale_value="$(localectl show -p Locale --value 2>/dev/null | sed -nE 's/^LANG=//p' | head -n 1)"
fi
if [[ -z "${locale_value}" ]]; then
  locale_value="$(locale | awk -F= '$1 == "LC_CTYPE" { gsub(/"/, "", $2); print $2 }')"
fi
if [[ -z "${locale_value}" || "${locale_value}" == "C" || "${locale_value}" == "POSIX" ]]; then
  locale_value="C.UTF-8"
fi

ssh_port="22"
if command -v systemctl >/dev/null 2>&1; then
  detected_ssh_port="$(
    systemctl show ssh.socket -p Listen --value --no-pager 2>/dev/null \
      | sed -nE 's/.*:([0-9]+) \(Stream\).*/\1/p' \
      | head -n 1
  )"
  if [[ -n "${detected_ssh_port}" ]]; then
    ssh_port="${detected_ssh_port}"
  fi
fi
if [[ "${ssh_port}" == "22" ]] && command -v ss >/dev/null 2>&1; then
  if ! ss -ltnH | awk '{print $4}' | grep -Eq '(^|:)22$' \
    && ss -ltnH | awk '{print $4}' | grep -Eq '(^|:)10198$'; then
    ssh_port="10198"
  fi
fi

cat <<EOF
# Generated by scripts/detect-host-user.sh for ${host_user}
COMPOSE_PROJECT_NAME=kde-in-web-browser
CONTAINER_NAME=kde-webtop

HOST_USER=${host_user}
HOST_UID=${host_uid}
HOST_GID=${host_gid}
HOST_HOME=${host_home}
CONTAINER_USER=${container_user}

TZ=${tz}
WEBTOP_LC_ALL=${locale_value}
TITLE=KDE in Web Browser

SHM_SIZE=2gb
DRI_DEVICE=/dev/dri
DRINODE=/dev/dri/renderD128
DRI_NODE=/dev/dri/renderD128
NVIDIA_VISIBLE_DEVICES=all
NVIDIA_DRIVER_CAPABILITIES=all
PIXELFLUX_WAYLAND=true
AUTO_GPU=true

SELKIES_CLIPBOARD_ENABLED=true
SELKIES_CLIPBOARD_IN_ENABLED=true
SELKIES_CLIPBOARD_OUT_ENABLED=true
SELKIES_ENABLE_BINARY_CLIPBOARD=true
SELKIES_COMMAND_ENABLED=true
SELKIES_USE_CSS_SCALING=false
SELKIES_FORCE_ALIGNED_RESOLUTION=true
SELKIES_SCALING_DPI=96,120,144,168,192,216,240,264,288
ENABLE_AUTO_HIDPI_DPI=true

SELKIES_ENCODER=x264enc,jpeg
SELKIES_FRAMERATE=8-60
SELKIES_VIDEO_BITRATE=8
SELKIES_RATE_CONTROL_MODE=cbr
SELKIES_ENABLE_RATE_CONTROL=true
SELKIES_H264_CRF=18-35
SELKIES_JPEG_QUALITY=80
SELKIES_AUDIO_BITRATE=128000
SELKIES_USE_PAINT_OVER_QUALITY=true
SELKIES_PAINT_OVER_JPEG_QUALITY=90
SELKIES_H264_PAINTOVER_CRF=18-28
SELKIES_H264_PAINTOVER_BURST_FRAMES=5

ENABLE_XWAYLAND_CLIPBOARD_BRIDGE=true

ENABLE_TERMINAL_INTEGRATION=true
HOST_SSH_HOST=host.docker.internal
HOST_SSH_PORT=${ssh_port}
HOST_SSH_TARGET=

ENABLE_THEME_SYNC=true
THEME_SYNC_LIGHT_SCHEME=BreezeLight
THEME_SYNC_DARK_SCHEME=BreezeDark
THEME_SYNC_LIGHT_LOOK_AND_FEEL=org.kde.breeze.desktop
THEME_SYNC_DARK_LOOK_AND_FEEL=org.kde.breezedark.desktop

ENABLE_WECHAT_QQ_MODULE=false
INSTALL_WECHAT=true
INSTALL_QQ=true
INSTALL_PCMANFM=true
AUTO_START_WECHAT=false
AUTO_START_QQ=false
WECHAT_PROFILE_DIR=${host_home}/.xwechat
WECHAT_FILES_DIR=${host_home}/xwechat_files
QQ_DATA_DIR="${host_home}/Tencent Files"

GATEWAY_BIND=127.0.0.1
GATEWAY_PORT=18080
GATEWAY_PUBLIC_BASE_URL=http://127.0.0.1:18080
GATEWAY_COOKIE_SECRET=change-me-generate-random-32-bytes
BETTER_AUTH_SECRET=change-me-generate-random-32-bytes
GATEWAY_SESSION_MAX_AGE_SECONDS=28800
GATEWAY_COOLDOWN_WINDOW_SECONDS=300
GATEWAY_COOLDOWN_MAX_FAILURES=5
GATEWAY_COOLDOWN_LOCK_SECONDS=300
PAM_HELPER_SOCKET=/run/kde-webtop-pam/helper.sock
EOF

echo "login through the gateway with the host account password" >&2
