#!/usr/bin/env bash
set -euo pipefail

host_user="${1:-${SUDO_USER:-${USER:-}}}"
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
data_root="${KDE_WEBTOP_DATA_ROOT:-${repo_root}/data}"

if [[ -z "${host_user}" ]]; then
  echo "usage: $0 [host-user]" >&2
  exit 2
fi

passwd_entry="$(getent passwd "${host_user}" || true)"
if [[ -z "${passwd_entry}" ]]; then
  echo "host user not found: ${host_user}" >&2
  exit 1
fi

host_uid="$(printf '%s\n' "${passwd_entry}" | awk -F: '{print $3}')"
host_gid="$(printf '%s\n' "${passwd_entry}" | awk -F: '{print $4}')"
host_home="$(printf '%s\n' "${passwd_entry}" | awk -F: '{print $6}')"
container_user="docker_${host_user}"
host_machine="$(hostname -s 2>/dev/null || hostname 2>/dev/null || printf 'host')"
host_machine="${host_machine%%.*}"
host_machine="$(printf '%s' "${host_machine}" | tr -c '[:alnum:]_.-' '_')"
host_machine="${host_machine##_}"
host_machine="${host_machine%%_}"
if [[ -z "${host_machine}" ]]; then
  host_machine="host"
fi
container_hostname="docker_${host_machine}"

tz="Etc/UTC"
if command -v timedatectl >/dev/null 2>&1; then
  detected_tz="$(timedatectl show -p Timezone --value 2>/dev/null || true)"
  if [[ -n "${detected_tz}" ]]; then
    tz="${detected_tz}"
  fi
elif [[ -f /etc/timezone ]]; then
  detected_tz="$(sed -n '1p' /etc/timezone)"
  if [[ -n "${detected_tz}" ]]; then
    tz="${detected_tz}"
  fi
fi

read_plasma_locale() {
  local file="$1"
  local group="$2"
  local key="$3"

  [[ -f "${file}" ]] || return 0
  awk -F= -v target_group="${group}" -v target_key="${key}" '
    /^\[/ {
      current = $0
      gsub(/^\[|\]$/, "", current)
      next
    }
    current == target_group && $1 == target_key {
      print $2
      exit
    }
  ' "${file}"
}

read_pam_environment() {
  local file="$1"
  local key="$2"

  [[ -f "${file}" ]] || return 0
  awk -v target_key="${key}" '
    $1 == target_key {
      for (i = 2; i <= NF; i++) {
        if ($i ~ /^DEFAULT=/) {
          value = $i
          sub(/^DEFAULT=/, "", value)
          gsub(/^"|"$/, "", value)
          print value
          exit
        }
      }
    }
    index($0, target_key "=") == 1 {
      value = $0
      sub("^" target_key "=", "", value)
      gsub(/^"|"$/, "", value)
      print value
      exit
    }
  ' "${file}"
}

normalize_locale() {
  local value="$1"
  value="${value%\"}"
  value="${value#\"}"
  case "${value}" in
    ""|C|POSIX)
      return 0
      ;;
    *)
      printf '%s\n' "${value}"
      ;;
  esac
}

derive_language_from_locale() {
  local value="$1"
  value="${value%%.*}"
  value="${value%%@*}"
  case "${value}" in
    ""|C|POSIX|C.UTF-8)
      printf 'en_US\n'
      ;;
    *)
      printf '%s\n' "${value}"
      ;;
  esac
}

plasma_locale_file="${host_home}/.config/plasma-localerc"
pam_environment_file="${host_home}/.pam_environment"

locale_value="$(normalize_locale "$(read_plasma_locale "${plasma_locale_file}" "Formats" "LANG")")"
if [[ -z "${locale_value}" ]]; then
  locale_value="$(normalize_locale "$(read_pam_environment "${pam_environment_file}" "LANG")")"
fi
if [[ -z "${locale_value}" ]] && command -v localectl >/dev/null 2>&1; then
  locale_value="$(normalize_locale "$(localectl show -p Locale --value 2>/dev/null | sed -nE 's/^LANG=//p' | head -n 1)")"
fi
if [[ -z "${locale_value}" ]]; then
  locale_value="$(normalize_locale "$(locale | awk -F= '$1 == "LC_CTYPE" { gsub(/"/, "", $2); print $2 }')")"
fi
if [[ -z "${locale_value}" ]]; then
  locale_value="C.UTF-8"
fi

language_value="$(normalize_locale "$(read_plasma_locale "${plasma_locale_file}" "Translations" "LANGUAGE")")"
if [[ -z "${language_value}" ]]; then
  language_value="$(normalize_locale "$(read_pam_environment "${pam_environment_file}" "LANGUAGE")")"
fi
if [[ -z "${language_value}" ]]; then
  language_value="$(derive_language_from_locale "${locale_value}")"
else
  language_value="${language_value%%.*}"
fi

ssh_port="22"
if command -v systemctl >/dev/null 2>&1; then
  detected_ssh_port="$(
    systemctl show ssh.socket -p Listen --value --no-pager 2>/dev/null \
      | sed -nE 's/.*:([0-9]+) \(Stream\).*/\1/p' \
      | head -n 1
  )"
  if [[ -n "${detected_ssh_port}" ]]; then
    ssh_port="${detected_ssh_port}"
  fi
fi
if [[ "${ssh_port}" == "22" ]] && command -v ss >/dev/null 2>&1; then
  if ! ss -ltnH | awk '{print $4}' | grep -Eq '(^|:)22$' \
    && ss -ltnH | awk '{print $4}' | grep -Eq '(^|:)10198$'; then
    ssh_port="10198"
  fi
fi

cat <<EOF
# Generated by scripts/deployment/actions/detect-host-user.sh for ${host_user}
COMPOSE_PROJECT_NAME=kde-in-web-browser
CONTAINER_NAME=kde-webtop
WEBTOP_IMAGE=kde-webtop:wechat-qq
NGINX_IMAGE=nginx:mainline-alpine
FRPC_IMAGE=snowdreamtech/frpc:nightly
CLOUDFLARED_IMAGE=cloudflare/cloudflared:latest

HOST_USER=${host_user}
HOST_UID=${host_uid}
HOST_GID=${host_gid}
HOST_HOME=${data_root}/home/${host_user}
CONTAINER_USER=${container_user}
CONTAINER_HOSTNAME=${container_hostname}

EXPOSURE_METHOD=local
NETWORK_EXPOSURE=unknown
NETWORK_EXPOSURE_REASON=not_detected
NETWORK_ROUTE_IPV4=
NETWORK_ROUTE_IFACE=
NETWORK_PUBLIC_IPV4=
NETWORK_PUBLIC_IP_SERVICE=https://api.ipify.org
NETWORK_DEFAULT_SSLIP_DOMAIN=
NETWORK_PORT_80_STATE=unknown
NETWORK_PORT_443_STATE=unknown

TZ=${tz}
WEBTOP_LANG=${locale_value}
WEBTOP_LANGUAGE=${language_value}
WEBTOP_LC_ALL=${locale_value}
TITLE=KDE in Web Browser

SHM_SIZE=2gb
DRI_DEVICE=/dev/dri
DRINODE=/dev/dri/renderD128
DRI_NODE=/dev/dri/renderD128
NVIDIA_VISIBLE_DEVICES=all
NVIDIA_DRIVER_CAPABILITIES=all
PIXELFLUX_WAYLAND=true
AUTO_GPU=true

SELKIES_CLIPBOARD_ENABLED=true
SELKIES_CLIPBOARD_IN_ENABLED=true
SELKIES_CLIPBOARD_OUT_ENABLED=true
SELKIES_ENABLE_BINARY_CLIPBOARD=true
SELKIES_COMMAND_ENABLED=true
SELKIES_USE_CSS_SCALING=false
SELKIES_FORCE_ALIGNED_RESOLUTION=true
SELKIES_SCALING_DPI=96,120,144,168,192,216,240,264,288
ENABLE_AUTO_HIDPI_DPI=true

SELKIES_ENCODER=x264enc,jpeg
SELKIES_FRAMERATE=8-60
SELKIES_VIDEO_BITRATE=8
SELKIES_RATE_CONTROL_MODE=cbr
SELKIES_ENABLE_RATE_CONTROL=true
SELKIES_H264_CRF=18-35
SELKIES_JPEG_QUALITY=80
SELKIES_AUDIO_BITRATE=128000
SELKIES_USE_PAINT_OVER_QUALITY=true
SELKIES_PAINT_OVER_JPEG_QUALITY=90
SELKIES_H264_PAINTOVER_CRF=18-28
SELKIES_H264_PAINTOVER_BURST_FRAMES=5

ENABLE_XWAYLAND_CLIPBOARD_BRIDGE=true

ENABLE_TERMINAL_INTEGRATION=true
HOST_SSH_HOST=host.docker.internal
HOST_SSH_PORT=${ssh_port}
HOST_SSH_TARGET=
HOST_SSH_KEY=/config/.ssh/kde-webtop-host-ed25519
SYNC_HOST_TERMINAL_ASSETS=true
SYNC_HOST_TERMINAL_SYSTEM_FONT_MATCHES=true

ENABLE_THEME_SYNC=true
THEME_SYNC_LIGHT_SCHEME=BreezeLight
THEME_SYNC_DARK_SCHEME=BreezeDark
THEME_SYNC_LIGHT_LOOK_AND_FEEL=org.kde.breeze.desktop
THEME_SYNC_DARK_LOOK_AND_FEEL=org.kde.breezedark.desktop

ENABLE_WECHAT_QQ_MODULE=true
INSTALL_WECHAT=true
INSTALL_QQ=true
INSTALL_PCMANFM=true
AUTO_START_WECHAT=false
AUTO_START_QQ=false
WECHAT_PROFILE_DIR=${data_root}/wechat/.xwechat
WECHAT_FILES_DIR=${data_root}/wechat/xwechat_files
QQ_DATA_DIR="${data_root}/qq/Tencent Files"

GATEWAY_BIND=127.0.0.1
GATEWAY_PORT=18080
GATEWAY_PUBLIC_BASE_URL=https://127.0.0.1:18080
GATEWAY_AUTH_PROVIDER=pam
GATEWAY_AUTH_INTERNAL_URI=/internal/pam/authz
GATEWAY_TLS_CERT=../ssl/kde-webtop.crt
GATEWAY_TLS_KEY=../ssl/kde-webtop.key
GATEWAY_TLS_SANS=IP:127.0.0.1,DNS:localhost
ACME_ENABLED=false
ACME_PROVIDER=sslip
ACME_DOMAIN=
ACME_EMAIL=
ACME_CERT_NAME=
ACME_HTTP_PORT=80
ACME_STAGING=false
ACME_ALLOW_NO_EMAIL=false
ACME_AUTO_RENEW=true
CLOUDFLARE_API_BASE_URL=https://api.cloudflare.com/client/v4
CLOUDFLARED_ORIGIN_URL=http://gateway-nginx:8080
CLOUDFLARE_API_TOKEN=
CLOUDFLARE_ACCOUNT_ID=
CLOUDFLARE_ZONE_ID=
CLOUDFLARE_HOSTNAME=
CLOUDFLARE_TUNNEL_NAME=kde-webtop-${host_user}
CLOUDFLARE_TUNNEL_ID=
CLOUDFLARED_TUNNEL_TOKEN=
CLOUDFLARE_DNS_PROXIED=true
PAM_AUTH_RUN_DIR=${data_root}/pam-auth/run
PAM_AUTH_STATE_DIR=${data_root}/pam-auth/state
PAM_AUTH_SOCKET_CONTAINER=/run/kde-pam-auth/pam-helper.sock
PAM_AUTH_SERVICE=kde-webtop
PAM_AUTH_ALLOWED_USERS=${host_user}
PAM_AUTH_SESSION_TTL_SECONDS=86400
PAM_AUTH_COOKIE_NAME=kde_pam_session
AUTHELIA_VERSION=4.39.20
AUTHELIA_CONFIG_DIR=${data_root}/authelia
AUTHELIA_PUBLIC_BASE_URLS=https://127.0.0.1:18080
AUTHELIA_USER=${host_user}
AUTHELIA_DISPLAY_NAME=KDE Web Desktop
AUTHELIA_EMAIL=${host_user}@localhost
EOF
