#!/usr/bin/env bash
set -euo pipefail

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
env_file="${ENV_FILE:-$repo_dir/.env}"
output_file="${1:-${BAOTA_COMPOSE_FILE:-$repo_dir/data/baota/docker-compose.yml}}"
output_env="${BAOTA_ENV_FILE:-$(dirname "$output_file")/.env}"
profiles_raw="${BAOTA_COMPOSE_PROFILES:-${COMPOSE_PROFILES:-frpc}}"

source_compose="$repo_dir/compose/webtop-kde.yml"

if [[ ! -f "$env_file" ]]; then
  echo "missing env file: $env_file" >&2
  echo "run scripts/deployment/install.sh or scripts/deployment/configure.sh first" >&2
  exit 1
fi

if [[ ! -f "$source_compose" ]]; then
  echo "missing compose template: $source_compose" >&2
  exit 1
fi

declare -A env=()

load_env_file() {
  local file="$1"
  local line key value
  [[ -f "$file" ]] || return 0
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line%$'\r'}"
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ "$line" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]] || continue
    key="${line%%=*}"
    value="${line#*=}"
    if [[ "$value" == \"*\" && "$value" == *\" ]]; then
      value="${value:1:${#value}-2}"
      value="${value//\\\"/\"}"
      value="${value//\\\\/\\}"
    elif [[ "$value" == \'*\' && "$value" == *\' ]]; then
      value="${value:1:${#value}-2}"
    fi
    env["$key"]="$value"
  done < "$file"
}

set_default() {
  local key="$1"
  local value="$2"
  if [[ -z "${env[$key]+x}" || -z "${env[$key]}" ]]; then
    env["$key"]="$value"
  fi
}

env_quote() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//\$/\\$}"
  value="${value//\`/\\\`}"
  printf '"%s"\n' "$value"
}

write_env_line() {
  local key="$1"
  printf '%s=' "$key" >>"$output_env"
  env_quote "${env[$key]-}" >>"$output_env"
}

write_env_section() {
  local title="$1"
  shift
  printf '\n# %s\n' "$title" >>"$output_env"
  local key
  for key in "$@"; do
    write_env_line "$key"
  done
}

compose_path_to_abs() {
  local value="$1"
  [[ -n "$value" ]] || return 0
  case "$value" in
    /*) realpath -m "$value" ;;
    *) realpath -m "$repo_dir/compose/$value" ;;
  esac
}

profile_enabled() {
  local target="$1"
  case "${profiles_raw,,}" in
    "" | "0" | "false" | "none" | "off" | "skip")
      return 1
      ;;
  esac
  local profile
  IFS=', ' read -r -a profiles <<<"$profiles_raw"
  for profile in "${profiles[@]}"; do
    [[ "$profile" == "$target" ]] && return 0
  done
  return 1
}

load_env_file "$repo_dir/.env.example"
load_env_file "$env_file"

set_default REPO_DIR "$repo_dir"
set_default WEBTOP_IMAGE "kde-webtop:wechat-qq"
set_default NGINX_IMAGE "nginx:mainline-alpine"
set_default FRPC_IMAGE "snowdreamtech/frpc:nightly"
set_default CLOUDFLARED_IMAGE "cloudflare/cloudflared:latest"

for key in \
  HOST_HOME \
  WECHAT_PROFILE_DIR \
  WECHAT_FILES_DIR \
  QQ_DATA_DIR \
  AUTHELIA_CONFIG_DIR \
  GATEWAY_TLS_CERT \
  GATEWAY_TLS_KEY \
  PAM_AUTH_RUN_DIR \
  PAM_AUTH_STATE_DIR \
  FRPC_CONFIG_FILE
do
  if [[ -n "${env[$key]-}" ]]; then
    env["$key"]="$(compose_path_to_abs "${env[$key]}")"
  fi
done

mkdir -p "$(dirname "$output_file")" "$(dirname "$output_env")"

{
  printf '# Generated by scripts/deployment/actions/render-baota-compose.sh\n'
  write_env_section "Baota compose paths" \
    REPO_DIR
  write_env_section "Compose project" \
    COMPOSE_PROJECT_NAME CONTAINER_NAME WEBTOP_IMAGE NGINX_IMAGE FRPC_IMAGE CLOUDFLARED_IMAGE
  write_env_section "Host user and project-local desktop home" \
    HOST_USER HOST_UID HOST_GID HOST_HOME CONTAINER_USER CONTAINER_HOSTNAME
  write_env_section "Network exposure detection" \
    EXPOSURE_METHOD NETWORK_EXPOSURE NETWORK_EXPOSURE_REASON NETWORK_ROUTE_IPV4 NETWORK_ROUTE_IFACE NETWORK_PUBLIC_IPV4 NETWORK_PUBLIC_IP_SERVICE NETWORK_DEFAULT_SSLIP_DOMAIN NETWORK_PORT_80_STATE NETWORK_PORT_443_STATE
  write_env_section "Container session" \
    TZ WEBTOP_LANG WEBTOP_LANGUAGE WEBTOP_LC_ALL TITLE
  write_env_section "Display and GPU" \
    SHM_SIZE DRI_DEVICE DRINODE DRI_NODE NVIDIA_VISIBLE_DEVICES NVIDIA_DRIVER_CAPABILITIES PIXELFLUX_WAYLAND AUTO_GPU
  write_env_section "Selkies clipboard and scaling" \
    SELKIES_CLIPBOARD_ENABLED SELKIES_CLIPBOARD_IN_ENABLED SELKIES_CLIPBOARD_OUT_ENABLED SELKIES_ENABLE_BINARY_CLIPBOARD SELKIES_COMMAND_ENABLED SELKIES_USE_CSS_SCALING SELKIES_FORCE_ALIGNED_RESOLUTION SELKIES_SCALING_DPI ENABLE_AUTO_HIDPI_DPI
  write_env_section "Selkies video and bandwidth" \
    SELKIES_ENCODER SELKIES_FRAMERATE SELKIES_VIDEO_BITRATE SELKIES_RATE_CONTROL_MODE SELKIES_ENABLE_RATE_CONTROL SELKIES_H264_CRF SELKIES_JPEG_QUALITY SELKIES_AUDIO_BITRATE SELKIES_USE_PAINT_OVER_QUALITY SELKIES_PAINT_OVER_JPEG_QUALITY SELKIES_H264_PAINTOVER_CRF SELKIES_H264_PAINTOVER_BURST_FRAMES
  write_env_section "Wayland/Xwayland clipboard" \
    ENABLE_XWAYLAND_CLIPBOARD_BRIDGE
  write_env_section "Terminal integration" \
    ENABLE_TERMINAL_INTEGRATION HOST_SSH_HOST HOST_SSH_PORT HOST_SSH_TARGET HOST_SSH_KEY SYNC_HOST_TERMINAL_ASSETS SYNC_HOST_TERMINAL_SYSTEM_FONT_MATCHES
  write_env_section "KDE theme sync" \
    ENABLE_THEME_SYNC THEME_SYNC_LIGHT_SCHEME THEME_SYNC_DARK_SCHEME THEME_SYNC_LIGHT_LOOK_AND_FEEL THEME_SYNC_DARK_LOOK_AND_FEEL
  write_env_section "WeChat/QQ module" \
    ENABLE_WECHAT_QQ_MODULE INSTALL_WECHAT INSTALL_QQ INSTALL_PCMANFM AUTO_START_WECHAT AUTO_START_QQ WECHAT_PROFILE_DIR WECHAT_FILES_DIR QQ_DATA_DIR
  write_env_section "Auth gateway" \
    GATEWAY_BIND GATEWAY_PORT GATEWAY_PUBLIC_BASE_URL GATEWAY_AUTH_PROVIDER GATEWAY_AUTH_INTERNAL_URI GATEWAY_TLS_CERT GATEWAY_TLS_KEY GATEWAY_TLS_SANS
  write_env_section "Public ACME" \
    ACME_ENABLED ACME_PROVIDER ACME_DOMAIN ACME_EMAIL ACME_CERT_NAME ACME_HTTP_PORT ACME_STAGING ACME_ALLOW_NO_EMAIL ACME_AUTO_RENEW
  write_env_section "Cloudflare Tunnel" \
    CLOUDFLARE_API_BASE_URL CLOUDFLARED_ORIGIN_URL CLOUDFLARE_API_TOKEN CLOUDFLARE_ACCOUNT_ID CLOUDFLARE_ZONE_ID CLOUDFLARE_HOSTNAME CLOUDFLARE_TUNNEL_NAME CLOUDFLARE_TUNNEL_ID CLOUDFLARED_TUNNEL_TOKEN CLOUDFLARE_DNS_PROXIED
  write_env_section "PAM auth helper" \
    PAM_AUTH_RUN_DIR PAM_AUTH_STATE_DIR PAM_AUTH_SOCKET_CONTAINER PAM_AUTH_SERVICE PAM_AUTH_ALLOWED_USERS PAM_AUTH_SESSION_TTL_SECONDS PAM_AUTH_COOKIE_NAME
  write_env_section "Authelia" \
    AUTHELIA_VERSION AUTHELIA_CONFIG_DIR AUTHELIA_PUBLIC_BASE_URLS AUTHELIA_USER AUTHELIA_DISPLAY_NAME AUTHELIA_EMAIL
  write_env_section "frpc" \
    FRPC_CONFIG_FILE
} >"$output_env"
chmod 0600 "$output_env"

include_frpc=false
if profile_enabled frpc; then
  include_frpc=true
fi
include_cloudflare=false
if profile_enabled cloudflare; then
  include_cloudflare=true
fi
include_cloudflare_quick=false
if profile_enabled cloudflare-quick; then
  include_cloudflare_quick=true
fi

{
  printf 'name: "${COMPOSE_PROJECT_NAME:-kde-in-web-browser}"\n'
  awk \
    -v include_frpc="$include_frpc" \
    -v include_cloudflare="$include_cloudflare" \
    -v include_cloudflare_quick="$include_cloudflare_quick" '
    NR == 1 && $0 == "---" { next }
    $0 ~ /^  frpc:$/ && include_frpc != "true" {
      skip_service = 1
      next
    }
    $0 ~ /^  cloudflared:$/ && include_cloudflare != "true" {
      skip_service = 1
      next
    }
    $0 ~ /^  cloudflared-quick:$/ && include_cloudflare_quick != "true" {
      skip_service = 1
      next
    }
    skip_service && $0 ~ /^  [A-Za-z0-9_-]+:$/ {
      skip_service = 0
    }
    skip_service { next }
    skip_profiles {
      if ($0 ~ /^      - /) next
      skip_profiles = 0
    }
    $0 ~ /^    profiles:$/ && (include_frpc == "true" || include_cloudflare == "true" || include_cloudflare_quick == "true") {
      skip_profiles = 1
      next
    }
    { print }
  ' "$source_compose" \
    | sed \
      -e 's#context: \.\.#context: "${REPO_DIR:?set REPO_DIR}"#' \
      -e 's#"\.\./custom-cont-init.d:/custom-cont-init.d:ro"#"${REPO_DIR:?set REPO_DIR}/custom-cont-init.d:/custom-cont-init.d:ro"#' \
      -e 's#"\.\./gateway/nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro"#"${REPO_DIR:?set REPO_DIR}/gateway/nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro"#'
} >"$output_file"
chmod 0644 "$output_file"

docker compose --env-file "$output_env" -f "$output_file" config --quiet
printf 'Rendered Baota compose: %s\n' "$output_file"
printf 'Rendered Baota env: %s\n' "$output_env"
